### ISSUE TITLE
Add rabbitMQ to extension bundles

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-rabbitmq-extension#106]
Adding tracking item to add RabbitMQ to extension bundles
https://github.com/Azure/azure-functions-extension-bundles

**Comment by yojagad** [comment]
Chatted with @soninaren and there are no plans to do preview-bundles. Extensions right now are added only after they're GA. Will add RabbitMQ after it's GA.

cc: @cachai2 @pragnagopa

**Comment by soninaren** [comment]
cc: @fabiocav

**Comment by pragnagopa** [comment]
I recommend tracking this item for GA. Without bundles, out-of-proc languages will include `bin` folder and `.csproj` when developing locally - We have received feedback in the past that `.csproj` and `bin` folder  is not native for non-dotnet functions

**Comment by yojagad** [comment]
This has been added to both linux and windows and is in the process of being deployed.
