### ISSUE TITLE
Remove creation of non-existing queue, dead letter queue and exchanges.

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-rabbitmq-extension#109]

**Comment by pragnagopa** [comment]
This is a breaking change. Please add more details in the description - after this change RabbitMQ trigger / bindings will only support existing queues

**Comment by yojagad** [comment]
With this change, users would have to configure the deadletter exchange and queue as specified here https://www.rabbitmq.com/dlx.html outside of the context of this binding . All rabbitMQ does it reject it with requeue parameter set to false like mentioned https://github.com/Azure/azure-functions-rabbitmq-extension/blob/dev/src/Trigger/RabbitMQListener.cs#L178 after a specific number of retries.

If the deadletter exchange and queue are configured right, they would end up there. Otherwise, they would lose the messages.
