### ISSUE TITLE
Document default values

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-rabbitmq-extension#116]
Although PrefetchCount is configurable now, the default for this needs to be documented

https://github.com/Azure/azure-functions-rabbitmq-extension/pull/114

cc: @cachai2

**Comment by cachai2** [comment]
https://github.com/MicrosoftDocs/azure-docs/issues/67044

**Comment by JatinSanghvi** [comment]
Prefetch count's default value is documented now. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-rabbitmq-trigger?tabs=csharp#hostjson-settings
