### ISSUE TITLE
The function doesn't consume messages.

### ISSUE THREAD

**Issue by sdgomez** [Azure/azure-functions-rabbitmq-extension#120]
Hi guys,
I'm trying to consume a message from RabbitMQ in an Azure Function which was created in NodeJs. I installed the  extension for  RabbitMQ in this manner:

- First, I installed .net on Linux like this:

        https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-

- Later:

`sudo func extensions install --package Microsoft.Azure.WebJobs.Extensions.RabbitMQ --version 0.2.2029-beta`

and I did this example:
`https://github.com/Azure/azure-functions-rabbitmq-extension/wiki/Samples-in-JavaScript `

The function Runs but doesn't consume messages from RabbitMQ.
![execution](https://user-images.githubusercontent.com/19391781/99595138-31c01c00-29c2-11eb-9f27-2cad8fd1304b.png)

I thank you for your collaboration :)

**Comment by yojagad** [comment]
Hello, the connectionStringSetting should be the name of an app setting (which is in local.settings.json if you're running this locally) which in turn should have connection string specified in the screenshot. 

If you tried the above suggestion and if it still doesn't work, please feel free to re-open this issue.
