### ISSUE TITLE
Consumption plan function won't consume message after timeout

### ISSUE THREAD

**Issue by sbobkin** [Azure/azure-functions-rabbitmq-extension#132]
Hi, 

I have a v3 runtime, Windows hosting, consumption plan function that uses this binding. It consumes messages correctly if the app is "active", however, it looks like if the function runtime period expires the function will no longer consume messages from a queue. 

If you load the function monitor or other page in Azure portal that seems to trigger the app pool to activate, then it will process the backlog of messages. 

Is this the expected behavior that if there's a break in Rabbit MQ queue messages greater than about 10 minutes~ (or big enough that the consumption plan app pool times out) that it breaks the consumption of messages go forward? 

I've confirmed this behavior across two different Rabbit MQ queues on the same consumption plan app pool. 

Thank you and let me know what additional details I can provide. 

My test function for this is: 

> [FunctionName("RabbitMQCloud")]
        public static void Run([RabbitMQTrigger("defaultqueue", ConnectionStringSetting = "connectionStringSettingCloud")] string message,
        ILogger log)
        {
            log.LogInformation($"Message received from RabbitMQ trigger: {message}");         
        }

**Comment by yojagad** [comment]
Thanks for the query. This extension is currently not supported for consumption plan and is only supported on dedicated and premium plans.
