### ISSUE TITLE
Add possibility to bind queueName in RabbitMQTriggerAttribute to Environment variable

### ISSUE THREAD

**Issue by RadekKapica** [Azure/azure-functions-rabbitmq-extension#139]
As for today you need a constant when specifying the queueName for the RabbitMQTrigger, to make more flexible Azure Functions it would be great if it was possible to "bind" the queueName to a Environment variable similarly to the connectionString.

**Comment by yojagad** [comment]
This is actually possible. In your trigger definition, instead of the queueName, please specify the setting name in the following format.

`"%RabbitMQQueueNameSetting%"`

Please feel free to reopen this issue if you have any more questions about this.
