### ISSUE TITLE
Consistency between trigger and binding

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-rabbitmq-extension#142]
- Trigger has `UserNameSetting` and `PasswordSetting` whereas binding has `UserName` and `Password`. These need to be consistent.

- Trigger expects the app setting name to be within "%%" if it's an app setting, whereas "%%" does not work with an output binding (it expects the app setting directly). https://github.com/Azure/azure-functions-rabbitmq-extension/blob/dev/src/Trigger/RabbitMQTriggerAttributeBindingProvider.cs#L58 vs https://github.com/Azure/azure-functions-rabbitmq-extension/blob/dev/src/Config/RabbitMQExtensionConfigProvider.cs#L83

**Comment by JatinSanghvi** [comment]
Assigned to myself. Good candidate for next major release.

**Comment by JatinSanghvi** [comment]
On seeing that more connection fields (enableSsl and vHost) had to be introduced in v2.x, it is decided to only support RabbitMQ connection URI in trigger and output bindings. We would be removing userName and password fields. This will make the question to bring consistency between them as irrelevant.
