### ISSUE TITLE
Message properties are not being sent in GRPC payload to out of process worker due to bug in RabbitMQ.Client 5.1.2

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-rabbitmq-extension#173]
When a producer sends a message with message properties, it is not being sent to the out-of-process worker, instead the type name string is being sent.

**Version:** WebJobs.Extensions.RabbitMQ version 1.1.0

_Note: This is not a code bug in the rabbitmq-extension, but a bug in the RabbitMQ.Client version 5.1.2, which we are using for WebJobs.Extensions.RabbitMQ 1.1.0_

#### Repro steps
1. Create a dotnet isolated worker to be used as a consumer of the message.
2. Publish a message with any properties other than `reply_to`. You may use the RabbitMQ admin portal to do this.
3. In the dotnet consumer project, setup a break point. Inspect the binding data on function context for `BasicProperties`. You can see that the value is a string of the type name (`RabbitMQ.Client.Framing.BasicProperties`) instead of a complex object. 

#### Why is this happening ?

I did a bit of investigation on why this is happening. Apparently, the host is trying to serialize the `BasicProperties` object while trying to create the GRPC payload to send to the worker, but it throws because accessing the `ReplyToAddress` property on `BasicProperties` object is throwing an exception. When an exception happens while trying to serialize the object, we call the `ToString` on the object in the catch block. In our case, the `ToString` call on this type is producing the type name value string.

![rabbitmq-host-throwing2](https://user-images.githubusercontent.com/144469/136809679-6db3bf3d-c6e9-4a4e-a82e-fd5d4b1c58d5.png)

The `WebJobs.Extensions.RabbitMQ version 1.1.0` is using `RabbitMQ.Client 5.1.2` package. If you look at the `ReplyToAddress` property implementation on 5.1.2, it is returning the result of `PublicationAddress.Parse(this.ReplyTo)`. 

![rabbitmqclient-replytoaddress-implementation](https://user-images.githubusercontent.com/144469/136809771-eeb3028b-19d7-4164-94c8-219f047b0552.png)

The `PublicationAddress.Parse` method is internally calling the `Regex.Match` method and passing the `reply_to` property value. [This method](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.match?view=net-5.0#System_Text_RegularExpressions_Regex_Match_System_String_) will throw an `ArgumentNullException` when the input is `null`, which is what is happening in our case.

![rabbitmqclient-parse-method](https://user-images.githubusercontent.com/144469/136809863-19fc54a4-eead-4ac8-80f8-545f6ecb39e8.png)

#### Mitigation

We will advise the users to always specify the `reply_to` property when publishing a message.

#### Fix

The RabbitMQ team had [fixed](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/828) this issue in May 2020. The fix is published in their [6.1.0](https://www.nuget.org/packages/RabbitMQ.Client/6.1.0) release. We should publish a new version of `WebJobs.Extensions.RabbitMQ` consuming the 6.1.0 RabbitMQ.Client package.

**Comment by kshyju** [comment]
cc @pragnagopa @yojagad

**Comment by pragnagopa** [comment]
cc @JatinSanghvi @lpapudippu

**Comment by kshyju** [comment]
@JatinSanghvi Any update on the progress of this fix?

**Comment by JatinSanghvi** [comment]
> @JatinSanghvi Any update on the progress of this fix?

@kshyju, was busy with other tasks. I will work on this one with priority starting 11/18.

**Comment by JatinSanghvi** [comment]
Verified that for out-of-proc Function app,:

`context.BindingContext.BindingData.TryGetValue("BasicProperties", out var basicProperties);` outputs:
- `RabbitMQ.Client.Framing.BasicProperties` without fix.
- `{"ContentType":null,"ContentEncoding":null,"Headers":{"hname":"aHZhbHVl"},"DeliveryMode":1,"Priority":0,"CorrelationId":null,"ReplyTo":null,"Expiration":null,"MessageId":null,"Timestamp":{"UnixTime":0},"Type":null,"UserId":null,"AppId":null,"ClusterId":null,"ProtocolClassId":60,"ProtocolClassName":"basic","Persistent":false,"ReplyToAddress":null}` with fix in place.
