### ISSUE TITLE
Code deleted after reorganizing code

### ISSUE THREAD

**Issue by aaguilartablada** [Azure/azure-functions-rabbitmq-extension#191]
Hello @JatinSanghvi.

After the last code refactor you have deleted code included in the pull request https://github.com/Azure/azure-functions-rabbitmq-extension/pull/178

It's very important defining connectionFactory.Ssl as I suggested you in mentioned PR:

```
                connectionFactory.Ssl = new SslOption
                {
                    Enabled = true,

                    // Set SNI in order to work for multiple RabbitMQ clusters located behind a LoadBalancer
                    ServerName = hostname,
                };
                if (skipCertificateValidation)
                {
                    connectionFactory.Ssl.AcceptablePolicyErrors =
                        SslPolicyErrors.RemoteCertificateNameMismatch | SslPolicyErrors.RemoteCertificateChainErrors;
                }
            }
```

With your changes, you don't allow configuring SSL while verifying the server certificate, which is incorrect. The developer needs to be provided with the ability to configure SSL verifying or not the server certificate.

Another piece of code that is lost is enabling SNI extension in SSL ClientHello. This is done setting ServerName in SslOption. Activating SNI is mandatory for those who have multiple rabbitMQ clusters behind a Load Balancer, as the Load Balancer route traffic based on SNI.

Please, recover the code. Thanks!!!!

**Comment by JatinSanghvi** [comment]
Hi @aaguilartablada , the connection string is enough to dictate whether SSL is enabled or not (See [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/d4b49cf9ffc2959398c499884a04e0fc333dc2af/projects/RabbitMQ.Client/client/api/ConnectionFactory.cs#L566-L568)). Also, the `ServerName` is always set to hostname by the RabbitMQ .NET client (See [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/d4b49cf9ffc2959398c499884a04e0fc333dc2af/projects/RabbitMQ.Client/client/api/ConnectionFactory.cs#L582)) so I believe that we have covered all the cases already. Let me know if you still think I have caused a regression by altering the code.

**Comment by aaguilartablada** [comment]
I guess it was introduced in a new version, as I tested with client v4 and SSL wasn't activated if you didn't indicate explicitly. Thanks for the info.
