### ISSUE TITLE
Headers?

### ISSUE THREAD

**Issue by magnayn** [Azure/azure-functions-rabbitmq-extension#197]
With Azure, I can use IAsyncCollector<ServiceBusMessage> and ServiceBusReceivedMessage[] in my functions in order to get access to the message headers.

This is important to extract metadata.

How is this achieved with the RabbitMQ binding?

**Comment by JatinSanghvi** [comment]
Can you try this? Bind the RabbitMQTrigger to `BasicDeliverEventArgs` type as in [here](https://github.com/Azure/azure-functions-rabbitmq-extension/blob/e100c191fc442abe02b611643d032789714763d3/extension/WebJobs.Extensions.RabbitMQ.Samples/RabbitMQSamples.cs#L96-L98). Then look for headers under `args.BasicProperties.Headers`.

**Comment by magnayn** [comment]
That works great!

Is there an equivalent for sending? We have been using (for ServiceBus)
IAsyncCollector<ServiceBusMessage> ?

**Comment by JatinSanghvi** [comment]
Hi, I had a suggestion but did not get time try it out myself earlier. Here is what is possible:

```cs
public static void BindToChannel(
    [TimerTrigger("01:00", RunOnStartup = true)] TimerInfo timer,
    [RabbitMQ(ConnectionStringSetting = "rabbitMQ")] IModel channel)
{
    channel.QueueDeclare(queue: "hello", false, false, false, null);

    IBasicProperties properties = channel.CreateBasicProperties();
    properties.Headers = new Dictionary<string, object> { ["headerName"] = "headerValue" };
    byte[] body = Encoding.UTF8.GetBytes("Hello World!");
    channel.BasicPublish(exchange: string.Empty, routingKey: "hello", properties, body);
}
```
