### ISSUE TITLE
RabbitMQAsyncCollector.AddAsync only adds to publish the body, not the properties

### ISSUE THREAD

**Issue by michaeltg17** [Azure/azure-functions-rabbitmq-extension#206]
Hi.

The parameter "message" in method "RabbitMQAsyncCollector.AddAsync" recieves the full BasicDeliverEventArgs object as ReadOnlyMemory<byte>, converted from the class PocoToBytesConverter. In the message, we have the BasicProperties, but this method is adding all the content of the message into the body parameter of the publlish method and setting the BasicProperties to null.

This causes the message to be published without the basic properties (although they are in the body section).

![image](https://user-images.githubusercontent.com/13167621/183890244-ae72eb38-d9a9-45ee-b539-dc123eac4b90.png)

**Comment by JatinSanghvi** [comment]
@michaeltg17, are you trying to set output binding parameter like below:

```cs
public static void UserFunction(
    [QueueTrigger("queue-name")] string message, // Could be any trigger.
    [RabbitMQ(QueueName = "queue")] IAsyncCollector<BasicDeliverEventArgs> outMessages)
````

RabbitMQ extension does not have a special handling for `BasicDeliverEventArgs` for output binding so it treats it as a regular POCO class, converts it to JSON string and passes it as body to the output RabbitMQ queue. It does have special handling for type `BasicDeliverEventArgs` in trigger binding.

I can be wrong, but I think the reason for this is `BasicDeliverEventArgs` is only used for accepting messages from queue, not for sending messages back. For that user needs to make direct request to `BasicPublishBatch.Add` method. Let me know if you can find an example that contradicts this.

If your function looks similar to the example above, you can change it to below to get handle of the RabbitMQ channel and publish messages on it directly passing in the properties:

```cs
public static void UserFunction(
    [QueueTrigger("queue-name")] string message, // Could be any trigger.
    [RabbitMQ(QueueName = "queue")] IModel channel)
{
    channel.BasicPublish(exchange: string.Empty, routingKey: <queue-name>, basicProperties: <your-properties>, body: body);
}
````
