### ISSUE TITLE
Nuget for this azure-functions-rabbitmq-extension

### ISSUE THREAD

**Issue by ankitvijay** [Azure/azure-functions-rabbitmq-extension#39]
Hi guys, 
This extension looks promising and we are eager to use it our project.

However,I could not locate link/ reference to NuGet Package for this library. Could you please point me the NuGet package if it already exists? Or else, are there any plans to have a NuGet package for this library?  Is yes, could you share the timelines?

- Thanks

**Comment by breno601** [comment]
Hi, does that mean you do not recommend to use this on production?

I was also trying to get it from nuget and couldn't find the package.

Thanks!

**Comment by ankitvijay** [comment]
Thanks @breno601 and @katiecai

**Comment by ankitvijay** [comment]
Hi guys, wanted to follow up on this and know if there are any updates on this issue. Thanks,

**Comment by ewinkiser** [comment]
Hello! Is the Nuget Package ready for this? We would like to use it; this extension is exactly what our requirements call out.
Thanks
@Mike Kiser

**Comment by anirudhgarg** [comment]
Yes it is available now: 
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.RabbitMQ

Please see this blog post as well:
https://dev.to/azure/announcing-the-rabbitmq-extension-for-azure-functions-2mbo
