### ISSUE TITLE
Figure out scaling metrics

### ISSUE THREAD

**Issue by katiecai** [Azure/azure-functions-rabbitmq-extension#46]
Currently, the only metrics we use for scaling are queue length. It'd be nice to be able to use time as a metric as well, but here are the issues with that:

- RabbitMQ has no implementation for message timestamp. We could use the [timestamp extension](https://github.com/rabbitmq/rabbitmq-message-timestamp) for this, or we could implement this ourselves (add a timestamp in the header of a message or something). Regardless of which method we were to choose, timestamp would need to be configured on the sending side as well. This complicates things more since it would require the user to add timestamp to their application even if they weren't planning to.
- RabbitMQ has no easy way for you to monitor queues. You can check the number of messages, but not the messages themselves - therefore we wouldn't even be able to check timestamp. From what I found we could do a no ACK (so that the messages stay in the queue even after consumption), but I think that would complicate the ACK protocol that we already have in place. There is also a [management plugin](https://www.rabbitmq.com/management.html) that allows you to monitor messages, but this consumes messages and requeues them. This could result in out-of-order messages in the queue, and I'm not sure we would want to requeue every message.

Lastly, RabbitMQ has a consumer count for queues which I'm not sure would be an important metric for scaling.

@pragnagopa Let me know what you think!

**Comment by katiecai** [comment]
scaling PR in progress: https://github.com/Azure/azure-functions-rabbitmq-extension/pulls

**Comment by JatinSanghvi** [comment]
I think just counting the queue lengths covers all situations. If the average time for processing a message becomes more than the average time interval between messages arriving to the queue, the queue size will start increasing and soon, that will trigger scaling out of the Function app. Let me know if I am not getting something and if there is an example scenario that counters my assumption.

**Comment by JatinSanghvi** [comment]
Closing the issue. We can create a new one if we ever find that the queue length exclusively is not the right choice for scaling decision for any situation.

**Comment by JatinSanghvi** [comment]
Afterthought: Message rate based scaling will be helpful if we have to react quickly to burst of incoming messages, rather than waiting for queue length to hit the threshold.
