### ISSUE TITLE
Is the output binding production ready?

### ISSUE THREAD

**Issue by creyke** [Azure/azure-functions-rabbitmq-extension#49]
I notice this project popped up recently...

I am already manually writing data from an Azure Function Cosmos Trigger to a RabbitMQ queue, but I am keen to pass the reconnect logic to an official binding and just populate a collection of messages as per your samples.

There is no NuGet package for this currently - does this mean it's still in development and not ready for production?

**Comment by creyke** [comment]
Please ignore, I read other recent issues and can see you are working towards a preview.

**Comment by 0if** [comment]
Is there any updates on this?
