### ISSUE TITLE
Make sure "connectionStringSetting" maps to "host"

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-rabbitmq-extension#55]
For KEDA to work, the metadata expects a property called "host", which is currently serialized as "connectionStringSetting".  I don't mind how we fix, but when I run `func kubernetes deploy` it should end up in kubernetes as "host".

Option 1: WE rename connectionStringSetting to host (believe this may be consistent with rabbitMQ SDKs - at least that's why we chose it for KEDA).

Option 2: We add some mapping logic in the core tools to do the mapping.  

I'm ok with either, but blocking KEDA until it is unblocked.

@ahmedelnably  as FYI

**Comment by pragnagopa** [comment]
I would prefer option 2 as it keeps extension consistent with rest of the bindings. @katiecai - please consider this a higher priority as using rabbitMQ trigger with KEDA is blocked until this is fixed.

**Comment by katiecai** [comment]
Closing as https://github.com/Azure/azure-functions-core-tools/pull/1544 solves this
