### ISSUE TITLE
Make the connection string an app setting

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-rabbitmq-extension#56]
Not sure if this means it has to be a connection string, but I know for other connection strings they are actually app settings too

https://github.com/Azure/azure-functions-rabbitmq-extension/blob/f655542427534270fb38052c3ab094b806fd3fe7/src/RabbitMQAttribute.cs#L41-L42

So would prefer this is an app setting too

**Comment by pragnagopa** [comment]
@brettsam / @fabiocav - Right now, we have explicitly chose to expose connection string setting as connectionString instead of an appSetting. Should we support both?

**Comment by jeffhollan** [comment]
The concrete thing I don't want to have happen is that when people publish they shouldn't add this to the connection string setting of the Antares stuff.  That would be a huge difference.  As long as it still an "App Setting" I'll let you all make the call

**Comment by brettsam** [comment]
Can you call this? https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Extensions/IConfigurationExtensions.cs#L78. That should do the fallback for you.

**Comment by brettsam** [comment]
Actually, where do you populate this @pragnagopa / @katiecai?  We can take another look... we really need an audit of how all the extensions do their resolution to see what discrepancies we have.

**Comment by katiecai** [comment]
@brettsam I think the connection string is automatically populated for the output binding. I know for the trigger we had to resolve it ourselves: https://github.com/Azure/azure-functions-rabbitmq-extension/blob/f655542427534270fb38052c3ab094b806fd3fe7/src/Trigger/RabbitMQTriggerAttributeBindingProvider.cs#L52 and https://github.com/Azure/azure-functions-rabbitmq-extension/blob/f655542427534270fb38052c3ab094b806fd3fe7/src/Utility.cs#L41-L55

**Comment by fabiocav** [comment]
The extensions we have today should be supporting both.

**Comment by katiecai** [comment]
I just verified on my function app that it does indeed populate regardless of whether you configure it as an app setting or connection string setting, as long as you set the ConnectionStringSetting to the right key
