### ISSUE TITLE
Add support for Java

### ISSUE THREAD

**Issue by katiecai** [Azure/azure-functions-rabbitmq-extension#60]

**Comment by jeffhollan** [comment]
Using custombinding is acceptable here but would need to be documentable, may be easier to just add library support https://github.com/Azure/azure-functions-java-library

**Comment by musa-pro** [comment]
Anyone has any luck in java?

**Comment by pragnagopa** [comment]
@jeffhollan  / @fabiocav  - I recommend following the approach for signalr and create Java annotations in this repo.

https://github.com/Azure/azure-functions-signalrservice-extension/tree/master/binding-library/java/src/main/java/com/microsoft/azure/functions/signalr

This allows keeping annotations and c# attributes in sync and can be released independently of azure-function-java-library

**Comment by pragnagopa** [comment]
cc @cachai2

**Comment by yojagad** [comment]
version 1.0.0-beta of azure-functions-java-library-rabbitmq is released to maven.
