### ISSUE TITLE
Make queue declaration optional

### ISSUE THREAD

**Issue by asud-solvve** [Azure/azure-functions-rabbitmq-extension#76]
Current implementation calls QueueDeclare automatically for RabbitMQTriggerAttribute queue.
I want to manage queues manually.
Could you, please, add some option to disable automatic queue declaration?

**Comment by ThejaChoudary** [comment]
@asud-solvve  Aplogies for the late reply.
Is this something your still experiencing with the latest version of Azure.

ThankYou  for the patience

**Comment by fabiocav** [comment]
@jeffhollan FYI for things to track for GA

/cc @pragnagopa

**Comment by pragnagopa** [comment]
@asud-solvve - We do support binding to the rabbitmq client

Here is an example on how to do that:

https://github.com/Azure/azure-functions-rabbitmq-extension/blob/214497c70e28208022c16acf71bf21fb77721da8/test/WebJobs.Extensions.RabbitMQ.Samples/RabbitMQSamples.cs#L79-L87

Is that what you are looking for?

**Comment by Elthan** [comment]
@pragnagopa Is this also possible to do with the RabbitMQTrigger? I want to bind to a queue with the trigger, but I do not have access to create queues, which results in getting rejected.

**Comment by cachai2** [comment]
@cachai2 for tracking

**Comment by yojagad** [comment]
Closing this since we removed the ability to create queue as part of extension that was tracked here #109
