### ISSUE TITLE
Add support to conditionally use this attribute vs another

### ISSUE THREAD

**Issue by chobot2014** [Azure/azure-functions-rabbitmq-extension#82]
We would like to have one function app codebase, one deployed to customers that want their software installed locally (and do not want literally anything to do with azure)  (using kubernetes)

for the other customers, we would like the functions to listen for a QueueTrigger instead.

Can you please help? Thanks!

**Comment by ThejaChoudary** [comment]
@chobot2014  Aplogies for the late reply.

Please check the [link1](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=csharp) [link2](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-storage-queue-triggered-function) for the Queue trigger , hope this would be helpful.

Thank You for the patience.
