### ISSUE TITLE
App Setting for Queue Name

### ISSUE THREAD

**Issue by RobBowman** [Azure/azure-functions-rabbitmq-extension#83]
The samples for triggered bindings illustrate the queue names hard-coded, such as:

`[RabbitMQTrigger("queue", Hostname = "localhost")]`

Is it possible to use a value from the Azure Functions config values instead? This would enable the same RabbitMQ instance to provide queues for multiple test environments; we could have "dev_input_queue", "uat_input_queue" etc.

**Comment by kentonbmax** [comment]
I support this feature request. Is anyone monitoring this repo? I see lots of needs triage.

**Comment by RobBowman** [comment]
It turns out this is supported after all! Thanks to Dan B for pointing this out The queue name param can simply be the name of an Azure Function environment variable wrapped with %s. The value from the environment variable will be substituted e.g.

`[RabbitMQTrigger("%myQueueNameVariable%", Hostname = "localhost")]`
