### ISSUE TITLE
Getting binding type(s) 'rabbitMQTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.

### ISSUE THREAD

**Issue by ashokbasutkar** [Azure/azure-functions-rabbitmq-extension#87]
running azure function locally for RabbitMQTrigger, there are no build error , but when the run the function  i am getting bellow error 

[3/12/2020 2:38:35 PM] Host started (2560ms)
[3/12/2020 2:38:35 PM] Job host started
[3/12/2020 2:38:35 PM] The 'Function1' function is in error: The binding type(s) 'rabbitMQTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
Hosting environment: Production

Please let me know how to reslove the issue

**Comment by litalb** [comment]
Same happens to me. Any updates about that issue?

**Comment by anirudhgarg** [comment]
Just wanted to make sure that you did indeed install the RabbitMQ extension. It is not available out of the box. 

https://dev.to/azure/announcing-the-rabbitmq-extension-for-azure-functions-2mbo

**Comment by 0if** [comment]
I am also facing this issue. I have the package installed.

**Comment by ankitkumarr** [comment]
Can you share your repro?

Most likely you function apps are using [Extension Bundle](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#extensionbundle), that brings in a collection of extensions and doesn't look at installed ones.

If this is the case, when you open `host.json`, you should see `extensionBundle: ` entry in the JSON. You can remove that JSON entry, and then re-install the RabbitMQ extension.

Please let me know if this works / doesn't work.

**Comment by kedar-rao** [comment]
I had the same issue and fixed it by adding this to my local.settings.json

  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  }
