### ISSUE TITLE
AzureWebJobStorage on baremetal kubernetes question

### ISSUE THREAD

**Issue by kentonbmax** [Azure/azure-functions-rabbitmq-extension#88]
Azure Functions 3.0
Dotnet Core 3.1

Currently we are running KEDA and kubernetes on bare metal. My Azure function which uses the rabbitmq trigger does not pick up messages correctly and shows a warning that the AzureWebJobStorage is required for rabbitmq trigger. I have tried setting the env to the defaulted appsettings value but the trigger still does not pickup messages correctly. Is there some updated documentation on the default settings required to run the azure function with a rabbitmq trigger as a docker image on baremetal kubernetes?

I wanted to add that we are not able to use Azure in the cloud at all. 

Values I have tried:
"AzureWebJobsStorage": "UseDevelopmentStorage=true", -- also tried false. 
"AzureWebJobsSecretStorageType": "Files",

**Comment by kentonbmax** [comment]
I wanted to add that we are using EF Core 3.1.2 not sure if this can cause issues.

**Comment by fabiocav** [comment]
@kentonbmax what is the message/log output you're seeing? Can you please share that information and stack details if present?
