### ISSUE TITLE
Support for RabbitMQ client 6.+

### ISSUE THREAD

**Issue by Elthan** [Azure/azure-functions-rabbitmq-extension#92]
Currently the extensions does not work with the Rabbit MQ client versions 6.+

Mainly it needs to be changed to support the change in body, from using byte arrays to ReadOnlyMemory.

**Comment by pragnagopa** [comment]
Need to investigate if this is breaking change. If yes, major version of the extension needs to be updated to add support for RabbitMQ client >=6.0

**Comment by cachai2** [comment]
Reevaluate in Nickel. Update with attribute consistency

**Comment by bacobart** [comment]
I tried to use this library in combination with MassTransit (like it works together with ServiceBus, https://masstransit-project.com/usage/transports/azure-sb.html ) and ran into exactly the mentioned issue regarding byte arrays vs ReadOnlyMemory. Until this library is updated to RabbitMQ.Client 6.x it will not be possible to use it together with MassTransit.

**Comment by bandmask** [comment]
What is status on this?

**Comment by Cogax** [comment]
Related: https://github.com/Azure/azure-functions-rabbitmq-extension/issues/89
